bfabric:
  app_runner: "git+https://github.com/fgcz/bfabricPy@main#subdirectory=bfabric_app_runner"
versions:
  - version: "0.1"
    commands:
      dispatch:
        type: shell
        command: uv run --script /home/bfabric/slurmworker/config/A373_STRING_GSEA/dispatch.py
      process:
        type: shell
        command: /home/bfabric/slurmworker/config/A373_STRING_GSEA/run.sh
      collect:
        type: shell
        command: echo "Hello world" && return 1
    submitter:
      name: slurm
