[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "a373-string-gsea"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
    "pyyaml","polars","requests","bfabric",'bfabric-scripts','loguru','pyexcelerate'
]


[tool.hatch.version]
path = "src/a373_string_gsea/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/a373_string_gsea tests}"

[tool.coverage.run]
source_pkgs = ["a373_string_gsea", "tests"]
branch = true
parallel = true
omit = [
  "src/a373_string_gsea/__about__.py",
]

[tool.coverage.paths]
a373_string_gsea = ["src/a373_string_gsea", "*/a373-string-gsea/src/a373_string_gsea"]
tests = ["tests", "*/a373-string-gsea/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
